image: ruby:2.7-alpine

pages:
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d public
    - cp -rv .well-known public/
  artifacts:
    paths:
      - public
