title: Johnny Santos blog
author:
  name: "Johnny Santos"
  email: johnnysantos@protonmail.com
description: >
  Johnny Santos personal blog.
  Soli Deo Gloria

url: https://johnnyasantos.com

theme: minima
permalink: pretty
excerpt_separator: <!--more-->

include: [".well-known"]
exclude:
  - Dockerfile
  - justfile
  - README.md

plugins:
  - jekyll-feed

sass:
  quiet_deps: true
  silence_deprecations: [import]

show_drafts: false
minima:
  date_format: "%b-%d-%Y"
  skin: dark
  show_excerpts: true

  nav_pages:
    - about.md

  social_links:
    - title: Github profile
      icon: github
      url: "https://github.com/johnnyasantoss"
    - title: X (Twitter) profile
      icon: x-twitter
      url: "https://x.com/johnnyasantos"
    - title: Nostr profile
      icon: globe far
      fa_namespace: classic
      url: "https://njump.me/npub1j0nyf54ndc6keq80xfyeqfumn2l23e3k79f33x5jsqxnut6a8dyqp74mu0"
    - title: Email Me
      icon: envelope far
      fa_namespace: classic
      url: "mailto:johnnysantos@protonmail.com"

